version: '3'
services:
  backend:
    build: ./server
    ports:
      - '8080:8080'
    volumes:
      - ./server:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - mongodb

  frontend:
    build: ./client
    ports:
      - '5173:5173'
    volumes:
      - ./client:/app
    depends_on:
      - backend

  mongodb:
    image: mongo:4.4
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db
